### ISSUE TITLE
pollbot in an encrypted room?

### ISSUE THREAD

**Issue by RagingSquirrel** [shawnanastasio/matrix-pollbot#11]
How can I activate the Pollbot for encrypted rooms?
I can invite the bot to a room in which encryption is activated. 
But the Pollbot is not answering to any command like !pollhelp.

**Comment by shawnanastasio** [comment]
One of our upstream libraries needs to implement support for E2E encryption before this is possible. There's an issue tracking it [here](https://github.com/matrix-org/matrix-python-sdk/issues/100).
