### ISSUE TITLE
ImportError: No module named mhandler

### ISSUE THREAD

**Issue by joenas** [shawnanastasio/matrix-pollbot#2]
I installed this package and `matrix-bot-api` via pip, when trying to run the bot (`python pollbot.py`) this happens.

```
Traceback (most recent call last):
  File "pollbot.py", line 3, in <module>
    from matrix_bot_api.mregex_handler import MRegexHandler
  File "/usr/local/lib/python2.7/site-packages/matrix_bot_api/mregex_handler.py", line 6, in <module>
    from matrix_bot_api.mhandler import MHandler
ImportError: No module named mhandler
```

**Comment by shawnanastasio** [comment]
You'll need to use python 3. Neither `matrix_bot_api` nor `matrix-pollbot` is compatible with python 2.7.

**Comment by joenas** [comment]
Ah I see. Thanks! Maybe put it in the readme? :)

**Comment by shawnanastasio** [comment]
Done. Thanks for reminding me about this.
